language: python

python:
 - "3.4"
 - "3.5"
 # - "3.6"  # enable this when we merge 3.6 support for codetransformer

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

env: CC=gcc-7 CXX=g++-7

install:
 - pip install -e .[dev]

before_script:
 - flake8 gotenks

script:
 - py.test gotenks --verbose

notifications:
  email: false
